// Copyright © 2019 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protob/ecdsa-resharing.proto

package resharing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Round 1 data is broadcast to peers of the New Committee in this message.
type DGRound1Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EcdsaPubX     []byte                 `protobuf:"bytes,1,opt,name=ecdsa_pub_x,json=ecdsaPubX,proto3" json:"ecdsa_pub_x,omitempty"`
	EcdsaPubY     []byte                 `protobuf:"bytes,2,opt,name=ecdsa_pub_y,json=ecdsaPubY,proto3" json:"ecdsa_pub_y,omitempty"`
	VCommitment   []byte                 `protobuf:"bytes,3,opt,name=v_commitment,json=vCommitment,proto3" json:"v_commitment,omitempty"`
	Ssid          []byte                 `protobuf:"bytes,4,opt,name=ssid,proto3" json:"ssid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRound1Message) Reset() {
	*x = DGRound1Message{}
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRound1Message) ProtoMessage() {}

func (x *DGRound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRound1Message.ProtoReflect.Descriptor instead.
func (*DGRound1Message) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_resharing_proto_rawDescGZIP(), []int{0}
}

func (x *DGRound1Message) GetEcdsaPubX() []byte {
	if x != nil {
		return x.EcdsaPubX
	}
	return nil
}

func (x *DGRound1Message) GetEcdsaPubY() []byte {
	if x != nil {
		return x.EcdsaPubY
	}
	return nil
}

func (x *DGRound1Message) GetVCommitment() []byte {
	if x != nil {
		return x.VCommitment
	}
	return nil
}

func (x *DGRound1Message) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

// The Round 2 data is broadcast to other peers of the New Committee in this message.
type DGRound2Message1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaillierN     []byte                 `protobuf:"bytes,1,opt,name=paillier_n,json=paillierN,proto3" json:"paillier_n,omitempty"`
	ModProof      [][]byte               `protobuf:"bytes,2,rep,name=modProof,proto3" json:"modProof,omitempty"`
	NTilde        []byte                 `protobuf:"bytes,3,opt,name=n_tilde,json=nTilde,proto3" json:"n_tilde,omitempty"`
	H1            []byte                 `protobuf:"bytes,4,opt,name=h1,proto3" json:"h1,omitempty"`
	H2            []byte                 `protobuf:"bytes,5,opt,name=h2,proto3" json:"h2,omitempty"`
	Dlnproof_1    [][]byte               `protobuf:"bytes,6,rep,name=dlnproof_1,json=dlnproof1,proto3" json:"dlnproof_1,omitempty"`
	Dlnproof_2    [][]byte               `protobuf:"bytes,7,rep,name=dlnproof_2,json=dlnproof2,proto3" json:"dlnproof_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRound2Message1) Reset() {
	*x = DGRound2Message1{}
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRound2Message1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRound2Message1) ProtoMessage() {}

func (x *DGRound2Message1) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRound2Message1.ProtoReflect.Descriptor instead.
func (*DGRound2Message1) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_resharing_proto_rawDescGZIP(), []int{1}
}

func (x *DGRound2Message1) GetPaillierN() []byte {
	if x != nil {
		return x.PaillierN
	}
	return nil
}

func (x *DGRound2Message1) GetModProof() [][]byte {
	if x != nil {
		return x.ModProof
	}
	return nil
}

func (x *DGRound2Message1) GetNTilde() []byte {
	if x != nil {
		return x.NTilde
	}
	return nil
}

func (x *DGRound2Message1) GetH1() []byte {
	if x != nil {
		return x.H1
	}
	return nil
}

func (x *DGRound2Message1) GetH2() []byte {
	if x != nil {
		return x.H2
	}
	return nil
}

func (x *DGRound2Message1) GetDlnproof_1() [][]byte {
	if x != nil {
		return x.Dlnproof_1
	}
	return nil
}

func (x *DGRound2Message1) GetDlnproof_2() [][]byte {
	if x != nil {
		return x.Dlnproof_2
	}
	return nil
}

// The Round 2 "ACK" is broadcast to peers of the Old Committee in this message.
type DGRound2Message2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRound2Message2) Reset() {
	*x = DGRound2Message2{}
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRound2Message2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRound2Message2) ProtoMessage() {}

func (x *DGRound2Message2) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRound2Message2.ProtoReflect.Descriptor instead.
func (*DGRound2Message2) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_resharing_proto_rawDescGZIP(), []int{2}
}

// The Round 3 data is sent to peers of the New Committee in this message.
type DGRound3Message1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         []byte                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRound3Message1) Reset() {
	*x = DGRound3Message1{}
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRound3Message1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRound3Message1) ProtoMessage() {}

func (x *DGRound3Message1) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRound3Message1.ProtoReflect.Descriptor instead.
func (*DGRound3Message1) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_resharing_proto_rawDescGZIP(), []int{3}
}

func (x *DGRound3Message1) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

// The Round 3 data is broadcast to peers of the New Committee in this message.
type DGRound3Message2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VDecommitment [][]byte               `protobuf:"bytes,1,rep,name=v_decommitment,json=vDecommitment,proto3" json:"v_decommitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRound3Message2) Reset() {
	*x = DGRound3Message2{}
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRound3Message2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRound3Message2) ProtoMessage() {}

func (x *DGRound3Message2) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRound3Message2.ProtoReflect.Descriptor instead.
func (*DGRound3Message2) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_resharing_proto_rawDescGZIP(), []int{4}
}

func (x *DGRound3Message2) GetVDecommitment() [][]byte {
	if x != nil {
		return x.VDecommitment
	}
	return nil
}

// The Round 4 "ACK" is broadcast to peers of the Old and New Committees from the New Committee in this message.
type DGRound4Message2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRound4Message2) Reset() {
	*x = DGRound4Message2{}
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRound4Message2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRound4Message2) ProtoMessage() {}

func (x *DGRound4Message2) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRound4Message2.ProtoReflect.Descriptor instead.
func (*DGRound4Message2) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_resharing_proto_rawDescGZIP(), []int{5}
}

// The Round 4 message to peers of New Committees from the New Committee in this message.
type DGRound4Message1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacProof      [][]byte               `protobuf:"bytes,1,rep,name=facProof,proto3" json:"facProof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DGRound4Message1) Reset() {
	*x = DGRound4Message1{}
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DGRound4Message1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DGRound4Message1) ProtoMessage() {}

func (x *DGRound4Message1) ProtoReflect() protoreflect.Message {
	mi := &file_protob_ecdsa_resharing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DGRound4Message1.ProtoReflect.Descriptor instead.
func (*DGRound4Message1) Descriptor() ([]byte, []int) {
	return file_protob_ecdsa_resharing_proto_rawDescGZIP(), []int{6}
}

func (x *DGRound4Message1) GetFacProof() [][]byte {
	if x != nil {
		return x.FacProof
	}
	return nil
}

var File_protob_ecdsa_resharing_proto protoreflect.FileDescriptor

const file_protob_ecdsa_resharing_proto_rawDesc = "" +
	"\n" +
	"\x1cprotob/ecdsa-resharing.proto\x12\x1ebinance.tsslib.ecdsa.resharing\"\x88\x01\n" +
	"\x0fDGRound1Message\x12\x1e\n" +
	"\vecdsa_pub_x\x18\x01 \x01(\fR\tecdsaPubX\x12\x1e\n" +
	"\vecdsa_pub_y\x18\x02 \x01(\fR\tecdsaPubY\x12!\n" +
	"\fv_commitment\x18\x03 \x01(\fR\vvCommitment\x12\x12\n" +
	"\x04ssid\x18\x04 \x01(\fR\x04ssid\"\xc4\x01\n" +
	"\x10DGRound2Message1\x12\x1d\n" +
	"\n" +
	"paillier_n\x18\x01 \x01(\fR\tpaillierN\x12\x1a\n" +
	"\bmodProof\x18\x02 \x03(\fR\bmodProof\x12\x17\n" +
	"\an_tilde\x18\x03 \x01(\fR\x06nTilde\x12\x0e\n" +
	"\x02h1\x18\x04 \x01(\fR\x02h1\x12\x0e\n" +
	"\x02h2\x18\x05 \x01(\fR\x02h2\x12\x1d\n" +
	"\n" +
	"dlnproof_1\x18\x06 \x03(\fR\tdlnproof1\x12\x1d\n" +
	"\n" +
	"dlnproof_2\x18\a \x03(\fR\tdlnproof2\"\x12\n" +
	"\x10DGRound2Message2\"(\n" +
	"\x10DGRound3Message1\x12\x14\n" +
	"\x05share\x18\x01 \x01(\fR\x05share\"9\n" +
	"\x10DGRound3Message2\x12%\n" +
	"\x0ev_decommitment\x18\x01 \x03(\fR\rvDecommitment\"\x12\n" +
	"\x10DGRound4Message2\".\n" +
	"\x10DGRound4Message1\x12\x1a\n" +
	"\bfacProof\x18\x01 \x03(\fR\bfacProofB\x11Z\x0fecdsa/resharingb\x06proto3"

var (
	file_protob_ecdsa_resharing_proto_rawDescOnce sync.Once
	file_protob_ecdsa_resharing_proto_rawDescData []byte
)

func file_protob_ecdsa_resharing_proto_rawDescGZIP() []byte {
	file_protob_ecdsa_resharing_proto_rawDescOnce.Do(func() {
		file_protob_ecdsa_resharing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protob_ecdsa_resharing_proto_rawDesc), len(file_protob_ecdsa_resharing_proto_rawDesc)))
	})
	return file_protob_ecdsa_resharing_proto_rawDescData
}

var file_protob_ecdsa_resharing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protob_ecdsa_resharing_proto_goTypes = []any{
	(*DGRound1Message)(nil),  // 0: binance.tsslib.ecdsa.resharing.DGRound1Message
	(*DGRound2Message1)(nil), // 1: binance.tsslib.ecdsa.resharing.DGRound2Message1
	(*DGRound2Message2)(nil), // 2: binance.tsslib.ecdsa.resharing.DGRound2Message2
	(*DGRound3Message1)(nil), // 3: binance.tsslib.ecdsa.resharing.DGRound3Message1
	(*DGRound3Message2)(nil), // 4: binance.tsslib.ecdsa.resharing.DGRound3Message2
	(*DGRound4Message2)(nil), // 5: binance.tsslib.ecdsa.resharing.DGRound4Message2
	(*DGRound4Message1)(nil), // 6: binance.tsslib.ecdsa.resharing.DGRound4Message1
}
var file_protob_ecdsa_resharing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protob_ecdsa_resharing_proto_init() }
func file_protob_ecdsa_resharing_proto_init() {
	if File_protob_ecdsa_resharing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protob_ecdsa_resharing_proto_rawDesc), len(file_protob_ecdsa_resharing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protob_ecdsa_resharing_proto_goTypes,
		DependencyIndexes: file_protob_ecdsa_resharing_proto_depIdxs,
		MessageInfos:      file_protob_ecdsa_resharing_proto_msgTypes,
	}.Build()
	File_protob_ecdsa_resharing_proto = out.File
	file_protob_ecdsa_resharing_proto_goTypes = nil
	file_protob_ecdsa_resharing_proto_depIdxs = nil
}
