// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/ecdsa-resharing.proto

package resharing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// The Round 1 data is broadcast to peers of the New Committee in this message.
type DGRound1Message struct {
	EcdsaPubX            []byte   `protobuf:"bytes,1,opt,name=ecdsa_pub_x,json=ecdsaPubX,proto3" json:"ecdsa_pub_x,omitempty"`
	EcdsaPubY            []byte   `protobuf:"bytes,2,opt,name=ecdsa_pub_y,json=ecdsaPubY,proto3" json:"ecdsa_pub_y,omitempty"`
	VCommitment          []byte   `protobuf:"bytes,3,opt,name=v_commitment,json=vCommitment,proto3" json:"v_commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound1Message) Reset()         { *m = DGRound1Message{} }
func (m *DGRound1Message) String() string { return proto.CompactTextString(m) }
func (*DGRound1Message) ProtoMessage()    {}
func (*DGRound1Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d3ae1dc68dc295, []int{0}
}

func (m *DGRound1Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound1Message.Unmarshal(m, b)
}
func (m *DGRound1Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound1Message.Marshal(b, m, deterministic)
}
func (m *DGRound1Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound1Message.Merge(m, src)
}
func (m *DGRound1Message) XXX_Size() int {
	return xxx_messageInfo_DGRound1Message.Size(m)
}
func (m *DGRound1Message) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound1Message.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound1Message proto.InternalMessageInfo

func (m *DGRound1Message) GetEcdsaPubX() []byte {
	if m != nil {
		return m.EcdsaPubX
	}
	return nil
}

func (m *DGRound1Message) GetEcdsaPubY() []byte {
	if m != nil {
		return m.EcdsaPubY
	}
	return nil
}

func (m *DGRound1Message) GetVCommitment() []byte {
	if m != nil {
		return m.VCommitment
	}
	return nil
}

//
// The Round 2 data is broadcast to other peers of the New Committee in this message.
type DGRound2Message1 struct {
	PaillierN            []byte   `protobuf:"bytes,1,opt,name=paillier_n,json=paillierN,proto3" json:"paillier_n,omitempty"`
	PaillierProof        [][]byte `protobuf:"bytes,2,rep,name=paillier_proof,json=paillierProof,proto3" json:"paillier_proof,omitempty"`
	NTilde               []byte   `protobuf:"bytes,3,opt,name=n_tilde,json=nTilde,proto3" json:"n_tilde,omitempty"`
	H1                   []byte   `protobuf:"bytes,4,opt,name=h1,proto3" json:"h1,omitempty"`
	H2                   []byte   `protobuf:"bytes,5,opt,name=h2,proto3" json:"h2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound2Message1) Reset()         { *m = DGRound2Message1{} }
func (m *DGRound2Message1) String() string { return proto.CompactTextString(m) }
func (*DGRound2Message1) ProtoMessage()    {}
func (*DGRound2Message1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d3ae1dc68dc295, []int{1}
}

func (m *DGRound2Message1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound2Message1.Unmarshal(m, b)
}
func (m *DGRound2Message1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound2Message1.Marshal(b, m, deterministic)
}
func (m *DGRound2Message1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound2Message1.Merge(m, src)
}
func (m *DGRound2Message1) XXX_Size() int {
	return xxx_messageInfo_DGRound2Message1.Size(m)
}
func (m *DGRound2Message1) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound2Message1.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound2Message1 proto.InternalMessageInfo

func (m *DGRound2Message1) GetPaillierN() []byte {
	if m != nil {
		return m.PaillierN
	}
	return nil
}

func (m *DGRound2Message1) GetPaillierProof() [][]byte {
	if m != nil {
		return m.PaillierProof
	}
	return nil
}

func (m *DGRound2Message1) GetNTilde() []byte {
	if m != nil {
		return m.NTilde
	}
	return nil
}

func (m *DGRound2Message1) GetH1() []byte {
	if m != nil {
		return m.H1
	}
	return nil
}

func (m *DGRound2Message1) GetH2() []byte {
	if m != nil {
		return m.H2
	}
	return nil
}

//
// The Round 2 "ACK" is broadcast to peers of the Old Committee in this message.
type DGRound2Message2 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound2Message2) Reset()         { *m = DGRound2Message2{} }
func (m *DGRound2Message2) String() string { return proto.CompactTextString(m) }
func (*DGRound2Message2) ProtoMessage()    {}
func (*DGRound2Message2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d3ae1dc68dc295, []int{2}
}

func (m *DGRound2Message2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound2Message2.Unmarshal(m, b)
}
func (m *DGRound2Message2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound2Message2.Marshal(b, m, deterministic)
}
func (m *DGRound2Message2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound2Message2.Merge(m, src)
}
func (m *DGRound2Message2) XXX_Size() int {
	return xxx_messageInfo_DGRound2Message2.Size(m)
}
func (m *DGRound2Message2) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound2Message2.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound2Message2 proto.InternalMessageInfo

//
// The Round 3 data is sent to peers of the New Committee in this message.
type DGRound3Message1 struct {
	Share                []byte   `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound3Message1) Reset()         { *m = DGRound3Message1{} }
func (m *DGRound3Message1) String() string { return proto.CompactTextString(m) }
func (*DGRound3Message1) ProtoMessage()    {}
func (*DGRound3Message1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d3ae1dc68dc295, []int{3}
}

func (m *DGRound3Message1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound3Message1.Unmarshal(m, b)
}
func (m *DGRound3Message1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound3Message1.Marshal(b, m, deterministic)
}
func (m *DGRound3Message1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound3Message1.Merge(m, src)
}
func (m *DGRound3Message1) XXX_Size() int {
	return xxx_messageInfo_DGRound3Message1.Size(m)
}
func (m *DGRound3Message1) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound3Message1.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound3Message1 proto.InternalMessageInfo

func (m *DGRound3Message1) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

//
// The Round 3 data is broadcast to peers of the New Committee in this message.
type DGRound3Message2 struct {
	VDecommitment        [][]byte `protobuf:"bytes,1,rep,name=v_decommitment,json=vDecommitment,proto3" json:"v_decommitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound3Message2) Reset()         { *m = DGRound3Message2{} }
func (m *DGRound3Message2) String() string { return proto.CompactTextString(m) }
func (*DGRound3Message2) ProtoMessage()    {}
func (*DGRound3Message2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7d3ae1dc68dc295, []int{4}
}

func (m *DGRound3Message2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound3Message2.Unmarshal(m, b)
}
func (m *DGRound3Message2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound3Message2.Marshal(b, m, deterministic)
}
func (m *DGRound3Message2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound3Message2.Merge(m, src)
}
func (m *DGRound3Message2) XXX_Size() int {
	return xxx_messageInfo_DGRound3Message2.Size(m)
}
func (m *DGRound3Message2) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound3Message2.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound3Message2 proto.InternalMessageInfo

func (m *DGRound3Message2) GetVDecommitment() [][]byte {
	if m != nil {
		return m.VDecommitment
	}
	return nil
}

func init() {
	proto.RegisterType((*DGRound1Message)(nil), "DGRound1Message")
	proto.RegisterType((*DGRound2Message1)(nil), "DGRound2Message1")
	proto.RegisterType((*DGRound2Message2)(nil), "DGRound2Message2")
	proto.RegisterType((*DGRound3Message1)(nil), "DGRound3Message1")
	proto.RegisterType((*DGRound3Message2)(nil), "DGRound3Message2")
}

func init() { proto.RegisterFile("protob/ecdsa-resharing.proto", fileDescriptor_f7d3ae1dc68dc295) }

var fileDescriptor_f7d3ae1dc68dc295 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x69, 0xe7, 0x26, 0x7e, 0xab, 0x9b, 0x06, 0xc1, 0x1c, 0x54, 0x66, 0x41, 0xe8, 0x45,
	0x47, 0xbb, 0x93, 0x57, 0x1d, 0x78, 0x52, 0x46, 0xf1, 0xa0, 0x5e, 0x42, 0xbb, 0xc6, 0x35, 0xd0,
	0x26, 0x25, 0x4d, 0x8b, 0xfe, 0x19, 0xfe, 0xc7, 0xd2, 0x2c, 0x0d, 0x1b, 0x3b, 0xbe, 0xdf, 0xf7,
	0xe0, 0x3d, 0xde, 0x07, 0x57, 0x95, 0x14, 0x4a, 0xa4, 0x73, 0xba, 0xce, 0xea, 0xe4, 0x5e, 0xd2,
	0x3a, 0x4f, 0x24, 0xe3, 0x9b, 0x07, 0x8d, 0x7d, 0x05, 0xd3, 0xe5, 0x4b, 0x2c, 0x1a, 0x9e, 0x85,
	0xaf, 0xb4, 0xae, 0x93, 0x0d, 0x45, 0x37, 0x30, 0xd6, 0x5e, 0x52, 0x35, 0x29, 0xf9, 0xc1, 0xce,
	0xcc, 0x09, 0xbc, 0xf8, 0x44, 0xa3, 0x55, 0x93, 0x7e, 0xec, 0xdf, 0x7f, 0xb1, 0xbb, 0x7f, 0xff,
	0x44, 0xb7, 0xe0, 0xb5, 0x64, 0x2d, 0xca, 0x92, 0xa9, 0x92, 0x72, 0x85, 0x07, 0xda, 0x30, 0x6e,
	0x9f, 0x2d, 0xf2, 0xff, 0x1c, 0x38, 0x33, 0xb1, 0x91, 0x89, 0x0d, 0xd1, 0x35, 0x40, 0x95, 0xb0,
	0xa2, 0x60, 0x54, 0x12, 0xde, 0xc7, 0xf6, 0xe4, 0x0d, 0xdd, 0xc1, 0xc4, 0x9e, 0x2b, 0x29, 0xc4,
	0x37, 0x76, 0x67, 0x83, 0xc0, 0x8b, 0x4f, 0x7b, 0xba, 0xea, 0x20, 0xba, 0x84, 0x63, 0x4e, 0x14,
	0x2b, 0x32, 0x6a, 0x82, 0x47, 0xfc, 0xbd, 0x53, 0x68, 0x02, 0x6e, 0x1e, 0xe2, 0x23, 0xcd, 0xdc,
	0x3c, 0xd4, 0x3a, 0xc2, 0x43, 0xa3, 0x23, 0x1f, 0x1d, 0x54, 0x8a, 0xfc, 0xc0, 0xb2, 0x85, 0xad,
	0x79, 0x01, 0xc3, 0x6e, 0x42, 0x6a, 0x1a, 0x6e, 0x85, 0xff, 0x78, 0xe0, 0x8c, 0xba, 0xc6, 0x2d,
	0xc9, 0xe8, 0xce, 0x14, 0xce, 0xb6, 0x71, 0xbb, 0xdc, 0x81, 0x4f, 0xe7, 0x5f, 0x53, 0x3d, 0xde,
	0xdc, 0xfe, 0x26, 0x1d, 0xe9, 0xe7, 0x2c, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x15, 0x9e, 0x5b,
	0xb0, 0xbc, 0x01, 0x00, 0x00,
}
