// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/message.proto

package tss

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Wrapper for TSS messages, often read by the transport layer and not itself sent over the wire
type MessageWrapper struct {
	// Metadata optionally un-marshalled and used by the transport to route this message.
	IsBroadcast bool `protobuf:"varint,1,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	// Metadata optionally un-marshalled and used by the transport to route this message.
	IsToOldCommittee bool `protobuf:"varint,2,opt,name=is_to_old_committee,json=isToOldCommittee,proto3" json:"is_to_old_committee,omitempty"`
	// Metadata optionally un-marshalled and used by the transport to route this message.
	From *MessageWrapper_PartyID `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// Metadata optionally un-marshalled and used by the transport to route this message.
	To []*MessageWrapper_PartyID `protobuf:"bytes,4,rep,name=to,proto3" json:"to,omitempty"`
	// This field is actually what is sent through the wire and consumed on the other end by UpdateFromBytes.
	// An Any contains an arbitrary serialized message as bytes, along with a URL that
	// acts as a globally unique identifier for and resolves to that message's type.
	Message              *any.Any `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWrapper) Reset()         { *m = MessageWrapper{} }
func (m *MessageWrapper) String() string { return proto.CompactTextString(m) }
func (*MessageWrapper) ProtoMessage()    {}
func (*MessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_5be430ad0e7f3d12, []int{0}
}

func (m *MessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWrapper.Unmarshal(m, b)
}
func (m *MessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWrapper.Marshal(b, m, deterministic)
}
func (m *MessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWrapper.Merge(m, src)
}
func (m *MessageWrapper) XXX_Size() int {
	return xxx_messageInfo_MessageWrapper.Size(m)
}
func (m *MessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWrapper proto.InternalMessageInfo

func (m *MessageWrapper) GetIsBroadcast() bool {
	if m != nil {
		return m.IsBroadcast
	}
	return false
}

func (m *MessageWrapper) GetIsToOldCommittee() bool {
	if m != nil {
		return m.IsToOldCommittee
	}
	return false
}

func (m *MessageWrapper) GetFrom() *MessageWrapper_PartyID {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MessageWrapper) GetTo() []*MessageWrapper_PartyID {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MessageWrapper) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

// PartyID represents a participant in the TSS protocol rounds.
// Note: The `id` and `moniker` are provided for convenience to allow you to track participants easier.
// The `id` is intended to be a unique string representation of `key` and `moniker` can be anything (even left blank).
type MessageWrapper_PartyID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Moniker              string   `protobuf:"bytes,2,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWrapper_PartyID) Reset()         { *m = MessageWrapper_PartyID{} }
func (m *MessageWrapper_PartyID) String() string { return proto.CompactTextString(m) }
func (*MessageWrapper_PartyID) ProtoMessage()    {}
func (*MessageWrapper_PartyID) Descriptor() ([]byte, []int) {
	return fileDescriptor_5be430ad0e7f3d12, []int{0, 0}
}

func (m *MessageWrapper_PartyID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWrapper_PartyID.Unmarshal(m, b)
}
func (m *MessageWrapper_PartyID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWrapper_PartyID.Marshal(b, m, deterministic)
}
func (m *MessageWrapper_PartyID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWrapper_PartyID.Merge(m, src)
}
func (m *MessageWrapper_PartyID) XXX_Size() int {
	return xxx_messageInfo_MessageWrapper_PartyID.Size(m)
}
func (m *MessageWrapper_PartyID) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWrapper_PartyID.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWrapper_PartyID proto.InternalMessageInfo

func (m *MessageWrapper_PartyID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageWrapper_PartyID) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *MessageWrapper_PartyID) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageWrapper)(nil), "MessageWrapper")
	proto.RegisterType((*MessageWrapper_PartyID)(nil), "MessageWrapper.PartyID")
}

func init() { proto.RegisterFile("protob/message.proto", fileDescriptor_5be430ad0e7f3d12) }

var fileDescriptor_5be430ad0e7f3d12 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x59, 0x3a, 0xad, 0x7b, 0x1b, 0x63, 0xc4, 0x81, 0x71, 0xa7, 0xea, 0xc5, 0x81, 0x98,
	0x82, 0x7e, 0x02, 0xa7, 0x1e, 0x3c, 0x88, 0x12, 0x04, 0xc1, 0x4b, 0x49, 0xd7, 0xac, 0x84, 0x35,
	0x7d, 0x25, 0x89, 0x87, 0x7e, 0x2a, 0xbf, 0xa2, 0x98, 0x2e, 0x07, 0x2f, 0xde, 0xf2, 0xde, 0xff,
	0x97, 0xfc, 0xf3, 0x83, 0x65, 0x67, 0xd1, 0x63, 0x99, 0x1b, 0xe5, 0x9c, 0xac, 0x15, 0x0f, 0xe3,
	0xea, 0xbc, 0x46, 0xac, 0x1b, 0x95, 0x0f, 0xe1, 0xd7, 0x2e, 0x97, 0x6d, 0x3f, 0x44, 0x97, 0xdf,
	0x04, 0xe6, 0x2f, 0x03, 0xfc, 0x61, 0x65, 0xd7, 0x29, 0x4b, 0x2f, 0x60, 0xa6, 0x5d, 0x51, 0x5a,
	0x94, 0xd5, 0x56, 0x3a, 0xcf, 0x46, 0xd9, 0x68, 0x7d, 0x22, 0xa6, 0xda, 0x6d, 0xe2, 0x8a, 0xde,
	0xc0, 0xa9, 0x76, 0x85, 0xc7, 0x02, 0x9b, 0xaa, 0xd8, 0xa2, 0x31, 0xda, 0x7b, 0xa5, 0x18, 0x09,
	0xe4, 0x42, 0xbb, 0x77, 0x7c, 0x6d, 0xaa, 0x87, 0xb8, 0xa7, 0xd7, 0x30, 0xde, 0x59, 0x34, 0x2c,
	0xc9, 0x46, 0xeb, 0xe9, 0xed, 0x19, 0xff, 0x5b, 0xc8, 0xdf, 0xa4, 0xf5, 0xfd, 0xf3, 0xa3, 0x08,
	0x10, 0xbd, 0x02, 0xe2, 0x91, 0x8d, 0xb3, 0xe4, 0x3f, 0x94, 0x78, 0xa4, 0x1c, 0xd2, 0x83, 0x26,
	0x83, 0xf0, 0xf0, 0x92, 0x0f, 0x9e, 0x3c, 0x7a, 0xf2, 0xfb, 0xb6, 0x17, 0x11, 0x5a, 0x3d, 0x41,
	0x7a, 0xb8, 0x4e, 0xe7, 0x40, 0x74, 0x15, 0xc4, 0x26, 0x82, 0xe8, 0x8a, 0x32, 0x48, 0x0d, 0xb6,
	0x7a, 0xaf, 0x6c, 0x70, 0x98, 0x88, 0x38, 0xd2, 0x05, 0x24, 0x7b, 0xd5, 0x87, 0x9f, 0xcf, 0xc4,
	0xef, 0x71, 0x93, 0x7e, 0x1e, 0xf1, 0xdc, 0x3b, 0x57, 0x1e, 0x87, 0x9a, 0xbb, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x18, 0xbf, 0xf1, 0xd7, 0x74, 0x01, 0x00, 0x00,
}
