# Read from go.mod rather than written out here. Spelling it out let it drift to
# the v3 path on the v4 branch, and since no target references MODULE, nothing
# failed to say so.
MODULE = $(shell go list -m)
PACKAGES = $(shell go list ./... | grep -v '/vendor/')

# The version that generated every .pb.go currently in the tree. protoc runs
# whichever protoc-gen-go is on PATH, so a different one rewrites all eight of
# them with no sign that anything happened -- which is how one of the eight spent
# a while generated by an older plugin than its neighbours. Refuse rather than
# regenerate: a wrong answer here is silent, and silence is the problem.
PROTOC_GEN_GO_VERSION = v1.36.11

all: protob test

########################################
### Protocol Buffers

check_protoc_gen_go:
	@have=$$(protoc-gen-go --version 2>/dev/null | awk '{print $$2}') ; \
	if [ "$$have" != "$(PROTOC_GEN_GO_VERSION)" ] ; then \
		echo "protoc-gen-go $(PROTOC_GEN_GO_VERSION) is required to regenerate; found $${have:-none}." ; \
		echo "Generating with another version rewrites all eight .pb.go files." ; \
		echo "  go install google.golang.org/protobuf/cmd/protoc-gen-go@$(PROTOC_GEN_GO_VERSION)" ; \
		echo "If you are deliberately moving to a new version, update PROTOC_GEN_GO_VERSION" ; \
		echo "in the Makefile in the same commit as the regenerated files." ; \
		exit 1 ; \
	fi

protob: check_protoc_gen_go
	@echo "--> Building Protocol Buffers"
	@for protocol in message signature ecdsa-keygen ecdsa-signing ecdsa-resharing eddsa-keygen eddsa-signing eddsa-resharing; do \
		echo "Generating $$protocol.pb.go" ; \
		protoc --go_out=. ./protob/$$protocol.proto ; \
	done

build: protob
	go fmt ./...

########################################
### Testing

test_unit:
	@echo "--> Running Unit Tests"
	@echo "!!! WARNING: This will take a long time :)"
	go clean -testcache
	go test -timeout 60m $(PACKAGES)

test_unit_race:
	@echo "--> Running Unit Tests (with Race Detection)"
	@echo "!!! WARNING: This will take a long time :)"
	go clean -testcache
	go test -timeout 60m -race $(PACKAGES)

test:
	make test_unit

########################################
### Pre Commit

pre_commit: build test

########################################

# To avoid unintended conflicts with file names, always add to .PHONY
# # unless there is a reason not to.
# # https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
.PHONY: check_protoc_gen_go protob build test_unit test_unit_race test

