[package]
name = "tss-lib-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
log = "0.4"
rand = "0.8"
num-integer = "0.1"
num-traits = "0.2" # Often needed with num crates
jacobi = "0.2"
once_cell = "1.19" # For static lazy initialization
num-prime = "0.4" # For primality testing
bytes = "1"
prost = "0.12"
tokio = { version = "1", features = ["full"] } # Async runtime
k256 = { version = "0.13", features = ["arithmetic"] } # SECP256k1 curve
p256 = { version = "0.13", features = ["arithmetic"] } # NIST P-256 curve
ed25519-dalek = "2.1" # Ed25519 signatures
sha2 = "0.10" # SHA-2 hashing algorithms
thiserror = "1.0" # Error handling
# Dependencies will be added here as needed during translation. 

[build-dependencies]
prost-build = "0.12"

[dev-dependencies]
# num-prime = "0.4" # No longer needed here, moved to regular dependencies 