// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/shared.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ECPoint struct {
	X                    []byte   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ECPoint) Reset()         { *m = ECPoint{} }
func (m *ECPoint) String() string { return proto.CompactTextString(m) }
func (*ECPoint) ProtoMessage()    {}
func (*ECPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a02941366730846, []int{0}
}

func (m *ECPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECPoint.Unmarshal(m, b)
}
func (m *ECPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECPoint.Marshal(b, m, deterministic)
}
func (m *ECPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECPoint.Merge(m, src)
}
func (m *ECPoint) XXX_Size() int {
	return xxx_messageInfo_ECPoint.Size(m)
}
func (m *ECPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ECPoint.DiscardUnknown(m)
}

var xxx_messageInfo_ECPoint proto.InternalMessageInfo

func (m *ECPoint) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *ECPoint) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

func init() {
	proto.RegisterType((*ECPoint)(nil), "ECPoint")
}

func init() { proto.RegisterFile("protob/shared.proto", fileDescriptor_1a02941366730846) }

var fileDescriptor_1a02941366730846 = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd2, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0x4d, 0xd1, 0x03, 0xf3, 0x94, 0x54, 0xb9, 0xd8,
	0x5d, 0x9d, 0x03, 0xf2, 0x33, 0xf3, 0x4a, 0x84, 0x78, 0xb8, 0x18, 0x2b, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x78, 0x82, 0x18, 0x2b, 0x40, 0xbc, 0x4a, 0x09, 0x26, 0x08, 0xaf, 0xd2, 0x89, 0x2b, 0x8a,
	0x43, 0x4f, 0x3f, 0x39, 0x3f, 0x37, 0x37, 0x3f, 0x2f, 0x89, 0x0d, 0xac, 0xd3, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x66, 0xd3, 0x86, 0x42, 0x50, 0x00, 0x00, 0x00,
}
