// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/signature.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Container for output signatures, mostly used for marshalling this data structure to a mobile app
type SignatureData struct {
	OneRoundData *SignatureData_OneRoundData `protobuf:"bytes,6,opt,name=one_round_data,json=oneRoundData,proto3" json:"one_round_data,omitempty"`
	Signature    []byte                      `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Ethereum-style recovery byte; only the first byte is relevant
	SignatureRecovery []byte `protobuf:"bytes,2,opt,name=signature_recovery,json=signatureRecovery,proto3" json:"signature_recovery,omitempty"`
	// Signature components R, S
	R []byte `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	// M represents the original message digest that was signed M
	M                    []byte   `protobuf:"bytes,5,opt,name=m,proto3" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureData) Reset()         { *m = SignatureData{} }
func (m *SignatureData) String() string { return proto.CompactTextString(m) }
func (*SignatureData) ProtoMessage()    {}
func (*SignatureData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73ad5e44f61b3fb, []int{0}
}

func (m *SignatureData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureData.Unmarshal(m, b)
}
func (m *SignatureData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureData.Marshal(b, m, deterministic)
}
func (m *SignatureData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureData.Merge(m, src)
}
func (m *SignatureData) XXX_Size() int {
	return xxx_messageInfo_SignatureData.Size(m)
}
func (m *SignatureData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureData.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureData proto.InternalMessageInfo

func (m *SignatureData) GetOneRoundData() *SignatureData_OneRoundData {
	if m != nil {
		return m.OneRoundData
	}
	return nil
}

func (m *SignatureData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignatureData) GetSignatureRecovery() []byte {
	if m != nil {
		return m.SignatureRecovery
	}
	return nil
}

func (m *SignatureData) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *SignatureData) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *SignatureData) GetM() []byte {
	if m != nil {
		return m.M
	}
	return nil
}

type SignatureData_OneRoundData struct {
	// Components to produce s = sum(s_i)
	KI     []byte `protobuf:"bytes,1,opt,name=k_i,json=kI,proto3" json:"k_i,omitempty"`
	SigmaI []byte `protobuf:"bytes,2,opt,name=sigma_i,json=sigmaI,proto3" json:"sigma_i,omitempty"`
	BigRX  []byte `protobuf:"bytes,3,opt,name=big_r_x,json=bigRX,proto3" json:"big_r_x,omitempty"`
	// Components for identifiable aborts during the final phase
	BigRY                []byte   `protobuf:"bytes,4,opt,name=big_r_y,json=bigRY,proto3" json:"big_r_y,omitempty"`
	BigRBarIX            []byte   `protobuf:"bytes,5,opt,name=big_r_bar_i_x,json=bigRBarIX,proto3" json:"big_r_bar_i_x,omitempty"`
	BigRBarIY            []byte   `protobuf:"bytes,6,opt,name=big_r_bar_i_y,json=bigRBarIY,proto3" json:"big_r_bar_i_y,omitempty"`
	BigSIX               []byte   `protobuf:"bytes,7,opt,name=big_s_i_x,json=bigSIX,proto3" json:"big_s_i_x,omitempty"`
	BigSIY               []byte   `protobuf:"bytes,8,opt,name=big_s_i_y,json=bigSIY,proto3" json:"big_s_i_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureData_OneRoundData) Reset()         { *m = SignatureData_OneRoundData{} }
func (m *SignatureData_OneRoundData) String() string { return proto.CompactTextString(m) }
func (*SignatureData_OneRoundData) ProtoMessage()    {}
func (*SignatureData_OneRoundData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73ad5e44f61b3fb, []int{0, 0}
}

func (m *SignatureData_OneRoundData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureData_OneRoundData.Unmarshal(m, b)
}
func (m *SignatureData_OneRoundData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureData_OneRoundData.Marshal(b, m, deterministic)
}
func (m *SignatureData_OneRoundData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureData_OneRoundData.Merge(m, src)
}
func (m *SignatureData_OneRoundData) XXX_Size() int {
	return xxx_messageInfo_SignatureData_OneRoundData.Size(m)
}
func (m *SignatureData_OneRoundData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureData_OneRoundData.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureData_OneRoundData proto.InternalMessageInfo

func (m *SignatureData_OneRoundData) GetKI() []byte {
	if m != nil {
		return m.KI
	}
	return nil
}

func (m *SignatureData_OneRoundData) GetSigmaI() []byte {
	if m != nil {
		return m.SigmaI
	}
	return nil
}

func (m *SignatureData_OneRoundData) GetBigRX() []byte {
	if m != nil {
		return m.BigRX
	}
	return nil
}

func (m *SignatureData_OneRoundData) GetBigRY() []byte {
	if m != nil {
		return m.BigRY
	}
	return nil
}

func (m *SignatureData_OneRoundData) GetBigRBarIX() []byte {
	if m != nil {
		return m.BigRBarIX
	}
	return nil
}

func (m *SignatureData_OneRoundData) GetBigRBarIY() []byte {
	if m != nil {
		return m.BigRBarIY
	}
	return nil
}

func (m *SignatureData_OneRoundData) GetBigSIX() []byte {
	if m != nil {
		return m.BigSIX
	}
	return nil
}

func (m *SignatureData_OneRoundData) GetBigSIY() []byte {
	if m != nil {
		return m.BigSIY
	}
	return nil
}

func init() {
	proto.RegisterType((*SignatureData)(nil), "SignatureData")
	proto.RegisterType((*SignatureData_OneRoundData)(nil), "SignatureData.OneRoundData")
}

func init() { proto.RegisterFile("protob/signature.proto", fileDescriptor_a73ad5e44f61b3fb) }

var fileDescriptor_a73ad5e44f61b3fb = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x18, 0xc4, 0xe5, 0x96, 0x26, 0xed, 0x47, 0x0a, 0xc2, 0x43, 0x31, 0x7f, 0x86, 0x88, 0xa9, 0x0b,
	0xa9, 0x04, 0x4f, 0x40, 0xc5, 0x92, 0x09, 0x29, 0x5d, 0x12, 0x16, 0xcb, 0x6e, 0xa3, 0xc8, 0xaa,
	0x12, 0xa3, 0x2f, 0x29, 0x6a, 0x5e, 0x8a, 0x87, 0xe2, 0x49, 0x90, 0x1d, 0x93, 0x06, 0xc6, 0xdf,
	0xdd, 0x59, 0x77, 0xf2, 0x07, 0x8b, 0x0f, 0xd4, 0x8d, 0x96, 0xab, 0x5a, 0x15, 0x95, 0x68, 0x0e,
	0x98, 0x47, 0x56, 0x78, 0xf8, 0x1a, 0xc3, 0x7c, 0xf3, 0xab, 0xbd, 0x8a, 0x46, 0xd0, 0x17, 0xb8,
	0xd0, 0x55, 0xce, 0x51, 0x1f, 0xaa, 0x1d, 0xdf, 0x89, 0x46, 0x30, 0x2f, 0x24, 0xcb, 0xf3, 0xa7,
	0xbb, 0xe8, 0x4f, 0x2e, 0x7a, 0xab, 0xf2, 0xc4, 0x64, 0x0c, 0x24, 0x81, 0x1e, 0x10, 0xbd, 0x87,
	0x59, 0xdf, 0xc3, 0x48, 0x48, 0x96, 0x41, 0x72, 0x12, 0xe8, 0x23, 0xd0, 0x1e, 0x38, 0xe6, 0x5b,
	0xfd, 0x99, 0x63, 0xcb, 0x46, 0x36, 0x76, 0xd5, 0x3b, 0x89, 0x33, 0x68, 0x00, 0x04, 0xd9, 0xd8,
	0xba, 0x04, 0x0d, 0xd5, 0xec, 0xac, 0xa3, 0xda, 0x50, 0xc9, 0x26, 0x1d, 0x95, 0xb7, 0xdf, 0x04,
	0x82, 0xe1, 0x2a, 0x7a, 0x09, 0xe3, 0x3d, 0x57, 0x6e, 0xc1, 0x68, 0x1f, 0xd3, 0x6b, 0xf0, 0x6b,
	0x55, 0x94, 0x82, 0x2b, 0xd7, 0xe7, 0x59, 0x8c, 0xe9, 0x02, 0x7c, 0xa9, 0x0a, 0x8e, 0xfc, 0xe8,
	0xaa, 0x26, 0x52, 0x15, 0x49, 0x7a, 0xd2, 0x5b, 0x57, 0x6a, 0xf5, 0x8c, 0x86, 0x30, 0xef, 0x74,
	0x29, 0x90, 0x2b, 0x7e, 0x74, 0x23, 0x66, 0xc6, 0x5d, 0x0b, 0x8c, 0xd3, 0xff, 0x89, 0xd6, 0xfe,
	0xe2, 0x20, 0x91, 0xd1, 0x1b, 0x30, 0xc0, 0x6b, 0xfb, 0xde, 0xef, 0xe6, 0x48, 0x55, 0x6c, 0xe2,
	0x74, 0x68, 0xb5, 0x6c, 0x3a, 0xb0, 0xb2, 0x35, 0xbc, 0x4f, 0xa3, 0xd5, 0x56, 0x97, 0xa5, 0xae,
	0xa4, 0x67, 0x6f, 0xf8, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x50, 0xd9, 0xfa, 0x71, 0xdd, 0x01,
	0x00, 0x00,
}
