// Copyright © 2019-2020 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signature.proto

package common

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Container for output signatures, mostly used for marshalling this data structure to a mobile app
type SignatureData struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Ethereum-style recovery byte; only the first byte is relevant
	SignatureRecovery []byte `protobuf:"bytes,2,opt,name=signature_recovery,json=signatureRecovery,proto3" json:"signature_recovery,omitempty"`
	// Signature components R, S
	R []byte `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	// M represents the original message digest that was signed M
	M                    []byte   `protobuf:"bytes,5,opt,name=m,proto3" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureData) Reset()         { *m = SignatureData{} }
func (m *SignatureData) String() string { return proto.CompactTextString(m) }
func (*SignatureData) ProtoMessage()    {}
func (*SignatureData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76962cacebaec211, []int{0}
}

func (m *SignatureData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureData.Unmarshal(m, b)
}
func (m *SignatureData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureData.Marshal(b, m, deterministic)
}
func (m *SignatureData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureData.Merge(m, src)
}
func (m *SignatureData) XXX_Size() int {
	return xxx_messageInfo_SignatureData.Size(m)
}
func (m *SignatureData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureData.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureData proto.InternalMessageInfo

func (m *SignatureData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignatureData) GetSignatureRecovery() []byte {
	if m != nil {
		return m.SignatureRecovery
	}
	return nil
}

func (m *SignatureData) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *SignatureData) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *SignatureData) GetM() []byte {
	if m != nil {
		return m.M
	}
	return nil
}

func init() {
	proto.RegisterType((*SignatureData)(nil), "binance.tsslib.SignatureData")
}

func init() { proto.RegisterFile("signature.proto", fileDescriptor_76962cacebaec211) }

var fileDescriptor_76962cacebaec211 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xce, 0x4c, 0xcf,
	0x4b, 0x2c, 0x29, 0x2d, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0xca, 0xcc,
	0x4b, 0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x29, 0x2e, 0xce, 0xc9, 0x4c, 0x52, 0x6a, 0x63, 0xe4, 0xe2,
	0x0d, 0x86, 0xa9, 0x71, 0x49, 0x2c, 0x49, 0x14, 0x92, 0xe1, 0xe2, 0x84, 0x6b, 0x92, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x09, 0x42, 0x08, 0x08, 0xe9, 0x72, 0x09, 0xc1, 0x39, 0xf1, 0x45, 0xa9, 0xc9,
	0xf9, 0x65, 0xa9, 0x45, 0x95, 0x12, 0x4c, 0x60, 0x65, 0x82, 0x70, 0x99, 0x20, 0xa8, 0x84, 0x10,
	0x0f, 0x17, 0x63, 0x91, 0x04, 0x33, 0x58, 0x96, 0xb1, 0x08, 0xc4, 0x2b, 0x96, 0x60, 0x81, 0xf0,
	0x8a, 0x41, 0xbc, 0x5c, 0x09, 0x56, 0x08, 0x2f, 0xd7, 0x89, 0x23, 0x8a, 0x2d, 0x39, 0x3f, 0x37,
	0x37, 0x3f, 0x2f, 0x89, 0x0d, 0xec, 0x52, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xe1,
	0x86, 0xde, 0xbc, 0x00, 0x00, 0x00,
}
