// Copyright © 2026 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

package common_test

import (
	"crypto/rand"
	"math/big"
	"testing"

	"github.com/bnb-chain/tss-lib/v4/common"
	"github.com/stretchr/testify/assert"
)

func TestIsUsableUnknownOrderModulus(t *testing.T) {
	// Honest 2048-bit composite (product of two primes generated by helpers).
	p := common.GetRandomPrimeInt(rand.Reader, 1024)
	q := common.GetRandomPrimeInt(rand.Reader, 1024)
	composite := new(big.Int).Mul(p, q)
	assert.True(t, common.IsUsableUnknownOrderModulus(composite, 2048))

	t.Run("nil", func(t *testing.T) {
		assert.False(t, common.IsUsableUnknownOrderModulus(nil, 2048))
	})
	t.Run("zero", func(t *testing.T) {
		assert.False(t, common.IsUsableUnknownOrderModulus(big.NewInt(0), 2048))
	})
	t.Run("negative", func(t *testing.T) {
		assert.False(t, common.IsUsableUnknownOrderModulus(big.NewInt(-1), 2048))
	})
	t.Run("even", func(t *testing.T) {
		even := new(big.Int).Lsh(composite, 1)
		assert.False(t, common.IsUsableUnknownOrderModulus(even, 2048))
	})
	t.Run("too small", func(t *testing.T) {
		assert.False(t, common.IsUsableUnknownOrderModulus(big.NewInt(15), 2048))
	})
	t.Run("prime", func(t *testing.T) {
		prime := common.GetRandomPrimeInt(rand.Reader, 2048)
		assert.False(t, common.IsUsableUnknownOrderModulus(prime, 2048))
	})
}

func TestIsCanonicalPaillierCiphertext(t *testing.T) {
	N := new(big.Int).Mul(big.NewInt(11), big.NewInt(13)) // 143
	NSq := new(big.Int).Mul(N, N)                         // 20449

	t.Run("valid", func(tt *testing.T) {
		assert.True(tt, common.IsCanonicalPaillierCiphertext(big.NewInt(7), N))
	})
	t.Run("nil c", func(tt *testing.T) {
		assert.False(tt, common.IsCanonicalPaillierCiphertext(nil, N))
	})
	t.Run("nil N", func(tt *testing.T) {
		assert.False(tt, common.IsCanonicalPaillierCiphertext(big.NewInt(7), nil))
	})
	t.Run("zero c", func(tt *testing.T) {
		assert.False(tt, common.IsCanonicalPaillierCiphertext(big.NewInt(0), N))
	})
	t.Run("negative c", func(tt *testing.T) {
		assert.False(tt, common.IsCanonicalPaillierCiphertext(big.NewInt(-1), N))
	})
	t.Run("c == N^2", func(tt *testing.T) {
		assert.False(tt, common.IsCanonicalPaillierCiphertext(NSq, N))
	})
	t.Run("c > N^2 (non-canonical)", func(tt *testing.T) {
		nonCanonical := new(big.Int).Add(NSq, big.NewInt(7))
		assert.False(tt, common.IsCanonicalPaillierCiphertext(nonCanonical, N))
	})
	t.Run("c shares factor with N", func(tt *testing.T) {
		assert.False(tt, common.IsCanonicalPaillierCiphertext(big.NewInt(11), N))
	})
}

func TestIsCanonicalGenerator(t *testing.T) {
	n := new(big.Int).Mul(big.NewInt(11), big.NewInt(13)) // 143
	assert.True(t, common.IsCanonicalGenerator(n, big.NewInt(2)))
	assert.True(t, common.IsCanonicalGenerator(n, big.NewInt(142)))

	t.Run("zero", func(t *testing.T) {
		assert.False(t, common.IsCanonicalGenerator(n, big.NewInt(0)))
	})
	t.Run("one", func(t *testing.T) {
		assert.False(t, common.IsCanonicalGenerator(n, big.NewInt(1)))
	})
	t.Run("equal to n", func(t *testing.T) {
		assert.False(t, common.IsCanonicalGenerator(n, n))
	})
	t.Run("non-coprime", func(t *testing.T) {
		assert.False(t, common.IsCanonicalGenerator(n, big.NewInt(11)))
	})
	t.Run("nil n", func(t *testing.T) {
		assert.False(t, common.IsCanonicalGenerator(nil, big.NewInt(2)))
	})
	t.Run("nil v", func(t *testing.T) {
		assert.False(t, common.IsCanonicalGenerator(n, nil))
	})
}
