// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/eddsa-signing.proto

package signing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Represents a BROADCAST message sent to all parties during Round 1 of the EDDSA TSS signing protocol.
type SignRound1Message struct {
	Commitment           []byte   `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRound1Message) Reset()         { *m = SignRound1Message{} }
func (m *SignRound1Message) String() string { return proto.CompactTextString(m) }
func (*SignRound1Message) ProtoMessage()    {}
func (*SignRound1Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d678aa6c179ddaa4, []int{0}
}

func (m *SignRound1Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRound1Message.Unmarshal(m, b)
}
func (m *SignRound1Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRound1Message.Marshal(b, m, deterministic)
}
func (m *SignRound1Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRound1Message.Merge(m, src)
}
func (m *SignRound1Message) XXX_Size() int {
	return xxx_messageInfo_SignRound1Message.Size(m)
}
func (m *SignRound1Message) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRound1Message.DiscardUnknown(m)
}

var xxx_messageInfo_SignRound1Message proto.InternalMessageInfo

func (m *SignRound1Message) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

//
// Represents a BROADCAST message sent to all parties during Round 2 of the EDDSA TSS signing protocol.
type SignRound2Message struct {
	DeCommitment         [][]byte `protobuf:"bytes,1,rep,name=de_commitment,json=deCommitment,proto3" json:"de_commitment,omitempty"`
	ProofAlphaX          []byte   `protobuf:"bytes,2,opt,name=proof_alpha_x,json=proofAlphaX,proto3" json:"proof_alpha_x,omitempty"`
	ProofAlphaY          []byte   `protobuf:"bytes,3,opt,name=proof_alpha_y,json=proofAlphaY,proto3" json:"proof_alpha_y,omitempty"`
	ProofT               []byte   `protobuf:"bytes,4,opt,name=proof_t,json=proofT,proto3" json:"proof_t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRound2Message) Reset()         { *m = SignRound2Message{} }
func (m *SignRound2Message) String() string { return proto.CompactTextString(m) }
func (*SignRound2Message) ProtoMessage()    {}
func (*SignRound2Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d678aa6c179ddaa4, []int{1}
}

func (m *SignRound2Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRound2Message.Unmarshal(m, b)
}
func (m *SignRound2Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRound2Message.Marshal(b, m, deterministic)
}
func (m *SignRound2Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRound2Message.Merge(m, src)
}
func (m *SignRound2Message) XXX_Size() int {
	return xxx_messageInfo_SignRound2Message.Size(m)
}
func (m *SignRound2Message) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRound2Message.DiscardUnknown(m)
}

var xxx_messageInfo_SignRound2Message proto.InternalMessageInfo

func (m *SignRound2Message) GetDeCommitment() [][]byte {
	if m != nil {
		return m.DeCommitment
	}
	return nil
}

func (m *SignRound2Message) GetProofAlphaX() []byte {
	if m != nil {
		return m.ProofAlphaX
	}
	return nil
}

func (m *SignRound2Message) GetProofAlphaY() []byte {
	if m != nil {
		return m.ProofAlphaY
	}
	return nil
}

func (m *SignRound2Message) GetProofT() []byte {
	if m != nil {
		return m.ProofT
	}
	return nil
}

//
// Represents a BROADCAST message sent to all parties during Round 3 of the EDDSA TSS signing protocol.
type SignRound3Message struct {
	Commitment           []byte   `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRound3Message) Reset()         { *m = SignRound3Message{} }
func (m *SignRound3Message) String() string { return proto.CompactTextString(m) }
func (*SignRound3Message) ProtoMessage()    {}
func (*SignRound3Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d678aa6c179ddaa4, []int{2}
}

func (m *SignRound3Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRound3Message.Unmarshal(m, b)
}
func (m *SignRound3Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRound3Message.Marshal(b, m, deterministic)
}
func (m *SignRound3Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRound3Message.Merge(m, src)
}
func (m *SignRound3Message) XXX_Size() int {
	return xxx_messageInfo_SignRound3Message.Size(m)
}
func (m *SignRound3Message) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRound3Message.DiscardUnknown(m)
}

var xxx_messageInfo_SignRound3Message proto.InternalMessageInfo

func (m *SignRound3Message) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

//
// Represents a BROADCAST message sent to all parties during Round 4 of the EDDSA TSS signing protocol.
type SignRound4Message struct {
	DeCommitment         [][]byte `protobuf:"bytes,1,rep,name=de_commitment,json=deCommitment,proto3" json:"de_commitment,omitempty"`
	ProofAlphaX          []byte   `protobuf:"bytes,2,opt,name=proof_alpha_x,json=proofAlphaX,proto3" json:"proof_alpha_x,omitempty"`
	ProofAlphaY          []byte   `protobuf:"bytes,3,opt,name=proof_alpha_y,json=proofAlphaY,proto3" json:"proof_alpha_y,omitempty"`
	ProofT               []byte   `protobuf:"bytes,4,opt,name=proof_t,json=proofT,proto3" json:"proof_t,omitempty"`
	VProofAlphaX         []byte   `protobuf:"bytes,5,opt,name=v_proof_alpha_x,json=vProofAlphaX,proto3" json:"v_proof_alpha_x,omitempty"`
	VProofAlphaY         []byte   `protobuf:"bytes,6,opt,name=v_proof_alpha_y,json=vProofAlphaY,proto3" json:"v_proof_alpha_y,omitempty"`
	VProofT              []byte   `protobuf:"bytes,7,opt,name=v_proof_t,json=vProofT,proto3" json:"v_proof_t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRound4Message) Reset()         { *m = SignRound4Message{} }
func (m *SignRound4Message) String() string { return proto.CompactTextString(m) }
func (*SignRound4Message) ProtoMessage()    {}
func (*SignRound4Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d678aa6c179ddaa4, []int{3}
}

func (m *SignRound4Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRound4Message.Unmarshal(m, b)
}
func (m *SignRound4Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRound4Message.Marshal(b, m, deterministic)
}
func (m *SignRound4Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRound4Message.Merge(m, src)
}
func (m *SignRound4Message) XXX_Size() int {
	return xxx_messageInfo_SignRound4Message.Size(m)
}
func (m *SignRound4Message) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRound4Message.DiscardUnknown(m)
}

var xxx_messageInfo_SignRound4Message proto.InternalMessageInfo

func (m *SignRound4Message) GetDeCommitment() [][]byte {
	if m != nil {
		return m.DeCommitment
	}
	return nil
}

func (m *SignRound4Message) GetProofAlphaX() []byte {
	if m != nil {
		return m.ProofAlphaX
	}
	return nil
}

func (m *SignRound4Message) GetProofAlphaY() []byte {
	if m != nil {
		return m.ProofAlphaY
	}
	return nil
}

func (m *SignRound4Message) GetProofT() []byte {
	if m != nil {
		return m.ProofT
	}
	return nil
}

func (m *SignRound4Message) GetVProofAlphaX() []byte {
	if m != nil {
		return m.VProofAlphaX
	}
	return nil
}

func (m *SignRound4Message) GetVProofAlphaY() []byte {
	if m != nil {
		return m.VProofAlphaY
	}
	return nil
}

func (m *SignRound4Message) GetVProofT() []byte {
	if m != nil {
		return m.VProofT
	}
	return nil
}

//
// Represents a BROADCAST message sent to all parties during Round 5 of the EDDSA TSS signing protocol.
type SignRound5Message struct {
	Commitment           []byte   `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRound5Message) Reset()         { *m = SignRound5Message{} }
func (m *SignRound5Message) String() string { return proto.CompactTextString(m) }
func (*SignRound5Message) ProtoMessage()    {}
func (*SignRound5Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d678aa6c179ddaa4, []int{4}
}

func (m *SignRound5Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRound5Message.Unmarshal(m, b)
}
func (m *SignRound5Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRound5Message.Marshal(b, m, deterministic)
}
func (m *SignRound5Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRound5Message.Merge(m, src)
}
func (m *SignRound5Message) XXX_Size() int {
	return xxx_messageInfo_SignRound5Message.Size(m)
}
func (m *SignRound5Message) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRound5Message.DiscardUnknown(m)
}

var xxx_messageInfo_SignRound5Message proto.InternalMessageInfo

func (m *SignRound5Message) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

//
// Represents a BROADCAST message sent to all parties during Round 6 of the EDDSA TSS signing protocol.
type SignRound6Message struct {
	DeCommitment         [][]byte `protobuf:"bytes,1,rep,name=de_commitment,json=deCommitment,proto3" json:"de_commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRound6Message) Reset()         { *m = SignRound6Message{} }
func (m *SignRound6Message) String() string { return proto.CompactTextString(m) }
func (*SignRound6Message) ProtoMessage()    {}
func (*SignRound6Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d678aa6c179ddaa4, []int{5}
}

func (m *SignRound6Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRound6Message.Unmarshal(m, b)
}
func (m *SignRound6Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRound6Message.Marshal(b, m, deterministic)
}
func (m *SignRound6Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRound6Message.Merge(m, src)
}
func (m *SignRound6Message) XXX_Size() int {
	return xxx_messageInfo_SignRound6Message.Size(m)
}
func (m *SignRound6Message) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRound6Message.DiscardUnknown(m)
}

var xxx_messageInfo_SignRound6Message proto.InternalMessageInfo

func (m *SignRound6Message) GetDeCommitment() [][]byte {
	if m != nil {
		return m.DeCommitment
	}
	return nil
}

//
// Represents a BROADCAST message sent to all parties during Round 3 of the EDDSA TSS signing protocol.
type SignRound7Message struct {
	S                    []byte   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRound7Message) Reset()         { *m = SignRound7Message{} }
func (m *SignRound7Message) String() string { return proto.CompactTextString(m) }
func (*SignRound7Message) ProtoMessage()    {}
func (*SignRound7Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d678aa6c179ddaa4, []int{6}
}

func (m *SignRound7Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRound7Message.Unmarshal(m, b)
}
func (m *SignRound7Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRound7Message.Marshal(b, m, deterministic)
}
func (m *SignRound7Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRound7Message.Merge(m, src)
}
func (m *SignRound7Message) XXX_Size() int {
	return xxx_messageInfo_SignRound7Message.Size(m)
}
func (m *SignRound7Message) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRound7Message.DiscardUnknown(m)
}

var xxx_messageInfo_SignRound7Message proto.InternalMessageInfo

func (m *SignRound7Message) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func init() {
	proto.RegisterType((*SignRound1Message)(nil), "SignRound1Message")
	proto.RegisterType((*SignRound2Message)(nil), "SignRound2Message")
	proto.RegisterType((*SignRound3Message)(nil), "SignRound3Message")
	proto.RegisterType((*SignRound4Message)(nil), "SignRound4Message")
	proto.RegisterType((*SignRound5Message)(nil), "SignRound5Message")
	proto.RegisterType((*SignRound6Message)(nil), "SignRound6Message")
	proto.RegisterType((*SignRound7Message)(nil), "SignRound7Message")
}

func init() { proto.RegisterFile("protob/eddsa-signing.proto", fileDescriptor_d678aa6c179ddaa4) }

var fileDescriptor_d678aa6c179ddaa4 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd2, 0x4f, 0x4d, 0x49, 0x29, 0x4e, 0xd4, 0x2d, 0xce, 0x4c, 0xcf, 0xcb, 0xcc, 0x4b,
	0xd7, 0x03, 0x0b, 0x2a, 0x19, 0x73, 0x09, 0x06, 0x67, 0xa6, 0xe7, 0x05, 0xe5, 0x97, 0xe6, 0xa5,
	0x18, 0xfa, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xc9, 0x71, 0x71, 0x25, 0xe7, 0xe7, 0xe6,
	0x66, 0x96, 0xe4, 0xa6, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x21, 0x89, 0x28,
	0xcd, 0x64, 0x44, 0xd2, 0x65, 0x04, 0xd3, 0xa5, 0xcc, 0xc5, 0x9b, 0x92, 0x1a, 0x8f, 0xa2, 0x91,
	0x59, 0x83, 0x27, 0x88, 0x27, 0x25, 0xd5, 0x19, 0x2e, 0x26, 0xa4, 0xc4, 0xc5, 0x5b, 0x50, 0x94,
	0x9f, 0x9f, 0x16, 0x9f, 0x98, 0x53, 0x90, 0x91, 0x18, 0x5f, 0x21, 0xc1, 0x04, 0x36, 0x9d, 0x1b,
	0x2c, 0xe8, 0x08, 0x12, 0x8b, 0x40, 0x57, 0x53, 0x29, 0xc1, 0x8c, 0xae, 0x26, 0x52, 0x48, 0x9c,
	0x8b, 0x1d, 0xa2, 0xa6, 0x44, 0x82, 0x05, 0x2c, 0xcb, 0x06, 0xe6, 0x86, 0xa0, 0x78, 0xc8, 0x98,
	0x58, 0x0f, 0x35, 0x33, 0x21, 0xe9, 0x32, 0x19, 0x54, 0x1e, 0x12, 0x52, 0xe5, 0xe2, 0x2f, 0x8b,
	0x47, 0xb5, 0x82, 0x15, 0xac, 0x80, 0xa7, 0x2c, 0x00, 0xc9, 0x0e, 0x0c, 0x65, 0x95, 0x12, 0x6c,
	0x18, 0xca, 0x22, 0x85, 0xa4, 0xb8, 0x38, 0x61, 0xca, 0x4a, 0x24, 0xd8, 0xc1, 0x0a, 0xd8, 0x21,
	0x0a, 0x50, 0x83, 0xce, 0x94, 0xd8, 0xa0, 0xb3, 0x40, 0xd2, 0x64, 0x46, 0x4a, 0xc8, 0x29, 0x29,
	0x22, 0xe9, 0x34, 0x87, 0xe9, 0xe4, 0xe1, 0x62, 0x2c, 0x86, 0xda, 0xc2, 0x58, 0xec, 0xc4, 0x1f,
	0xc5, 0x0b, 0x4e, 0xb4, 0xfa, 0xd0, 0x44, 0x9b, 0xc4, 0x06, 0x4e, 0xb5, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x48, 0x3e, 0x51, 0x46, 0xd3, 0x02, 0x00, 0x00,
}
