// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/message.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Wrapper for TSS messages
type Message struct {
	IsBroadcast      bool `protobuf:"varint,1,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	IsToOldCommittee bool `protobuf:"varint,2,opt,name=is_to_old_committee,json=isToOldCommittee,proto3" json:"is_to_old_committee,omitempty"`
	// An Any contains an arbitrary serialized message as bytes, along with a URL that
	// acts as a globally unique identifier for and resolves to that message's type.
	Message              *any.Any `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5be430ad0e7f3d12, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetIsBroadcast() bool {
	if m != nil {
		return m.IsBroadcast
	}
	return false
}

func (m *Message) GetIsToOldCommittee() bool {
	if m != nil {
		return m.IsToOldCommittee
	}
	return false
}

func (m *Message) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("protob/message.proto", fileDescriptor_5be430ad0e7f3d12) }

var fileDescriptor_5be430ad0e7f3d12 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd2, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x03, 0x73, 0xa5, 0x24, 0xd3,
	0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x21, 0x92, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95, 0x10, 0x29,
	0xa5, 0x6e, 0x46, 0x2e, 0x76, 0x5f, 0x88, 0x62, 0x21, 0x45, 0x2e, 0x9e, 0xcc, 0xe2, 0xf8, 0xa4,
	0xa2, 0xfc, 0xc4, 0x94, 0xe4, 0xc4, 0xe2, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0xee,
	0xcc, 0x62, 0x27, 0x98, 0x90, 0x90, 0x2e, 0x97, 0x70, 0x66, 0x71, 0x7c, 0x49, 0x7e, 0x7c, 0x7e,
	0x4e, 0x4a, 0x7c, 0x72, 0x7e, 0x6e, 0x6e, 0x66, 0x49, 0x49, 0x6a, 0xaa, 0x04, 0x13, 0x58, 0xa5,
	0x40, 0x66, 0x71, 0x48, 0xbe, 0x7f, 0x4e, 0x8a, 0x33, 0x4c, 0x5c, 0x48, 0x8f, 0x8b, 0x1d, 0xea,
	0x12, 0x09, 0x2e, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x11, 0x3d, 0x88, 0x53, 0xf4, 0x60, 0x4e, 0xd1,
	0x73, 0xcc, 0xab, 0x0c, 0x82, 0x29, 0x72, 0xe2, 0x8a, 0xe2, 0x28, 0x29, 0x2e, 0xd6, 0x2f, 0xcf,
	0x2c, 0x4a, 0x4d, 0x62, 0x03, 0x2b, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x8f, 0x63,
	0xf4, 0xd3, 0x00, 0x00, 0x00,
}
