name: Go Test
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: macOS-latest
    steps:

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.3
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Clean dependencies
        working-dierctory: ./v2
        run: go clean --modcache

      - name: Get dependencies
        working-directory: ./v2
        run: go mod tidy

      - name: Run Tests
        working-directory: ./v2
        run: make test_unit_race
