// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/eddsa-resharing.proto

package resharing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// The Round 1 data is broadcast to peers of the New Committee in this message.
type DGRound1Message struct {
	EddsaPubX            []byte   `protobuf:"bytes,1,opt,name=eddsa_pub_x,json=eddsaPubX,proto3" json:"eddsa_pub_x,omitempty"`
	EddsaPubY            []byte   `protobuf:"bytes,2,opt,name=eddsa_pub_y,json=eddsaPubY,proto3" json:"eddsa_pub_y,omitempty"`
	VCommitment          []byte   `protobuf:"bytes,3,opt,name=v_commitment,json=vCommitment,proto3" json:"v_commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound1Message) Reset()         { *m = DGRound1Message{} }
func (m *DGRound1Message) String() string { return proto.CompactTextString(m) }
func (*DGRound1Message) ProtoMessage()    {}
func (*DGRound1Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{0}
}

func (m *DGRound1Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound1Message.Unmarshal(m, b)
}
func (m *DGRound1Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound1Message.Marshal(b, m, deterministic)
}
func (m *DGRound1Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound1Message.Merge(m, src)
}
func (m *DGRound1Message) XXX_Size() int {
	return xxx_messageInfo_DGRound1Message.Size(m)
}
func (m *DGRound1Message) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound1Message.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound1Message proto.InternalMessageInfo

func (m *DGRound1Message) GetEddsaPubX() []byte {
	if m != nil {
		return m.EddsaPubX
	}
	return nil
}

func (m *DGRound1Message) GetEddsaPubY() []byte {
	if m != nil {
		return m.EddsaPubY
	}
	return nil
}

func (m *DGRound1Message) GetVCommitment() []byte {
	if m != nil {
		return m.VCommitment
	}
	return nil
}

//
// The Round 2 "ACK" is broadcast to peers of the Old Committee in this message.
type DGRound2Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound2Message) Reset()         { *m = DGRound2Message{} }
func (m *DGRound2Message) String() string { return proto.CompactTextString(m) }
func (*DGRound2Message) ProtoMessage()    {}
func (*DGRound2Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{1}
}

func (m *DGRound2Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound2Message.Unmarshal(m, b)
}
func (m *DGRound2Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound2Message.Marshal(b, m, deterministic)
}
func (m *DGRound2Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound2Message.Merge(m, src)
}
func (m *DGRound2Message) XXX_Size() int {
	return xxx_messageInfo_DGRound2Message.Size(m)
}
func (m *DGRound2Message) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound2Message.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound2Message proto.InternalMessageInfo

//
// The Round 3 data is sent to peers of the New Committee in this message.
type DGRound3Message1 struct {
	Share                []byte   `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound3Message1) Reset()         { *m = DGRound3Message1{} }
func (m *DGRound3Message1) String() string { return proto.CompactTextString(m) }
func (*DGRound3Message1) ProtoMessage()    {}
func (*DGRound3Message1) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{2}
}

func (m *DGRound3Message1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound3Message1.Unmarshal(m, b)
}
func (m *DGRound3Message1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound3Message1.Marshal(b, m, deterministic)
}
func (m *DGRound3Message1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound3Message1.Merge(m, src)
}
func (m *DGRound3Message1) XXX_Size() int {
	return xxx_messageInfo_DGRound3Message1.Size(m)
}
func (m *DGRound3Message1) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound3Message1.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound3Message1 proto.InternalMessageInfo

func (m *DGRound3Message1) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

//
// The Round 3 data is broadcast to peers of the New Committee in this message.
type DGRound3Message2 struct {
	VDecommitment        [][]byte `protobuf:"bytes,1,rep,name=v_decommitment,json=vDecommitment,proto3" json:"v_decommitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound3Message2) Reset()         { *m = DGRound3Message2{} }
func (m *DGRound3Message2) String() string { return proto.CompactTextString(m) }
func (*DGRound3Message2) ProtoMessage()    {}
func (*DGRound3Message2) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{3}
}

func (m *DGRound3Message2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound3Message2.Unmarshal(m, b)
}
func (m *DGRound3Message2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound3Message2.Marshal(b, m, deterministic)
}
func (m *DGRound3Message2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound3Message2.Merge(m, src)
}
func (m *DGRound3Message2) XXX_Size() int {
	return xxx_messageInfo_DGRound3Message2.Size(m)
}
func (m *DGRound3Message2) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound3Message2.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound3Message2 proto.InternalMessageInfo

func (m *DGRound3Message2) GetVDecommitment() [][]byte {
	if m != nil {
		return m.VDecommitment
	}
	return nil
}

//
// The Round 4 "ACK" is broadcast to peers of the Old and New Committees from the New Committee in this message.
type DGRound4Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DGRound4Message) Reset()         { *m = DGRound4Message{} }
func (m *DGRound4Message) String() string { return proto.CompactTextString(m) }
func (*DGRound4Message) ProtoMessage()    {}
func (*DGRound4Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{4}
}

func (m *DGRound4Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DGRound4Message.Unmarshal(m, b)
}
func (m *DGRound4Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DGRound4Message.Marshal(b, m, deterministic)
}
func (m *DGRound4Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DGRound4Message.Merge(m, src)
}
func (m *DGRound4Message) XXX_Size() int {
	return xxx_messageInfo_DGRound4Message.Size(m)
}
func (m *DGRound4Message) XXX_DiscardUnknown() {
	xxx_messageInfo_DGRound4Message.DiscardUnknown(m)
}

var xxx_messageInfo_DGRound4Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DGRound1Message)(nil), "DGRound1Message")
	proto.RegisterType((*DGRound2Message)(nil), "DGRound2Message")
	proto.RegisterType((*DGRound3Message1)(nil), "DGRound3Message1")
	proto.RegisterType((*DGRound3Message2)(nil), "DGRound3Message2")
	proto.RegisterType((*DGRound4Message)(nil), "DGRound4Message")
}

func init() { proto.RegisterFile("protob/eddsa-resharing.proto", fileDescriptor_cd99ebe69a0b0962) }

var fileDescriptor_cd99ebe69a0b0962 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd2, 0x4f, 0x4d, 0x49, 0x29, 0x4e, 0xd4, 0x2d, 0x4a, 0x2d, 0xce, 0x48, 0x2c, 0xca,
	0xcc, 0x4b, 0xd7, 0x03, 0x0b, 0x2b, 0x95, 0x70, 0xf1, 0xbb, 0xb8, 0x07, 0xe5, 0x97, 0xe6, 0xa5,
	0x18, 0xfa, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xc9, 0x71, 0x71, 0x83, 0xd5, 0xc6, 0x17,
	0x94, 0x26, 0xc5, 0x57, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x71, 0x82, 0x85, 0x02, 0x4a,
	0x93, 0x22, 0x50, 0xe5, 0x2b, 0x25, 0x98, 0x50, 0xe5, 0x23, 0x85, 0x14, 0xb9, 0x78, 0xca, 0xe2,
	0x93, 0xf3, 0x73, 0x73, 0x33, 0x4b, 0x72, 0x53, 0xf3, 0x4a, 0x24, 0x98, 0xc1, 0x0a, 0xb8, 0xcb,
	0x9c, 0xe1, 0x42, 0x4a, 0x82, 0x70, 0x5b, 0x8d, 0xa0, 0xb6, 0x2a, 0x69, 0x70, 0x09, 0x40, 0x85,
	0x8c, 0xa1, 0x42, 0x86, 0x42, 0x22, 0x5c, 0xac, 0x20, 0xd7, 0xa6, 0x42, 0xdd, 0x00, 0xe1, 0x28,
	0x59, 0x62, 0xa8, 0x34, 0x12, 0x52, 0xe5, 0xe2, 0x2b, 0x8b, 0x4f, 0x49, 0x45, 0xb2, 0x95, 0x51,
	0x81, 0x59, 0x83, 0x27, 0x88, 0xb7, 0xcc, 0x05, 0x49, 0x10, 0xc9, 0x5e, 0x13, 0xa8, 0x56, 0x27,
	0xc1, 0x28, 0x7e, 0xb0, 0xd3, 0xf5, 0xe1, 0x21, 0x93, 0xc4, 0x06, 0x0e, 0x1a, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0x00, 0xa7, 0x6e, 0x3a, 0x01, 0x00, 0x00,
}
